# Scientific Python
Lecturers = R. Patrick Xian, Santosh Adhikari, Sourin Dey<br>
Date = 07/2022
## 1. math -- built-in math

In [1]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [2]:
try:
    del math
except:
    pass
import math as m
from math import sin, pi, radians

In [3]:
sin(pi/2)

1.0

In [4]:
help(radians)

Help on built-in function radians in module math:

radians(...)
    radians(x)
    
    Convert angle x from degrees to radians.



In [5]:
sin(radians(30))

0.49999999999999994

In [6]:
m.floor(2.5), m.ceil(2.5)

(2, 3)

In [7]:
m.isnan(m.nan), m.isinf(m.inf)

(True, True)

In [8]:
frac, intg = m.modf(2.519)
print('The integer is {0:0}, the fraction is {1:0.3f}'.format(intg, frac))

The integer is 2.0, the fraction is 0.519


In [9]:
a = [0.1, 0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0., 0.1, 0.1]
sum(a), m.fsum(a)

(1.3000000000000003, 1.3)

In [10]:
m.e, m.e == m.exp(1)

(2.718281828459045, True)

## 2. numpy -- numeric operations

### 2.1 basic math
Read the list of functions [here](https://numpy.org/doc/stable/reference/index.html#reference)

### 2.2 numpy arrays
#### 2.2.1 array operations

In [50]:
import numpy as np

In [12]:
arr = np.array([-0.1,9.0,300,4])
arr, type(arr)

(array([-1.e-01,  9.e+00,  3.e+02,  4.e+00]), numpy.ndarray)

In [13]:
arr.ndim

1

In [14]:
arr[:, np.newaxis].squeeze()

array([-1.e-01,  9.e+00,  3.e+02,  4.e+00])

In [15]:
arr_properties = list(prop for prop in dir(arr) if not prop.startswith('__'))
print(arr_properties)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [16]:
arr.shape

(4,)

In [17]:
arr2d = np.atleast_2d(arr)
arr2d.shape

(1, 4)

In [18]:
arr2d.squeeze().shape

(4,)

In [19]:
arr2d

array([[-1.e-01,  9.e+00,  3.e+02,  4.e+00]])

In [20]:
arr2d == arr

array([[ True,  True,  True,  True]])

In [21]:
arr.mean()

78.225

In [22]:
arr.dtype

dtype('float64')

In [23]:
intarr = arr.astype('int')
intarr

array([  0,   9, 300,   4])

In [24]:
intarr.dtype

dtype('int32')

In [25]:
arr1 = np.array([[1,9,3,12],[0,5,4,2],[19,8,10,7]])
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [26]:
arr1.shape

(3, 4)

In [27]:
arr1.size

12

In [28]:
arr1.ravel()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [29]:
arr1.flatten()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [30]:
arr1.sum(), arr1.prod()

(80, 0)

In [31]:
arr1.reshape((2,6))

array([[ 1,  9,  3, 12,  0,  5],
       [ 4,  2, 19,  8, 10,  7]])

In [32]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [33]:
arr1.T

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [34]:
arr1.swapaxes(0,1)

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [35]:
np.prod(arr1.T == arr1.swapaxes(0,1))

1

#### 2.2.2 [array indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html)

In [36]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [37]:
arr1[0,:]

array([ 1,  9,  3, 12])

In [38]:
arr1[0,1]

9

In [39]:
arr1[1:10:2]

array([[0, 5, 4, 2]])

In [40]:
arr1[arr1 > 5]

array([ 9, 12, 19,  8, 10,  7])

In [41]:
# Output the array indices
np.argwhere(arr1 > 5)

array([[0, 1],
       [0, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [42]:
np.where(arr1 > 5)

(array([0, 0, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 1, 2, 3], dtype=int64))

In [43]:
arr1[_]

array([ 9, 12, 19,  8, 10,  7])

#### 2.2.3 [array broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [44]:
arr = np.array([1,2,3,4])

In [45]:
stacked_arr = np.tile(arr, (3,1))
stacked_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [46]:
np.broadcast_to(arr, (2,arr.size))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [47]:
stacked_arr + arr

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [48]:
stacked_arr * arr

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

#### Addition between a matrix (2D array) and a vector (1D array) using broadcasting

In [49]:
stacked_arr + arr[:-1]

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [51]:
stacked_arr.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [52]:
stacked_arr.T + arr[:-1]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

#### 2.2.4 dimensional operations
Useful for operations on multidimensional arrays

In [53]:
rarr = np.random.rand(14, 3, 2, 8)
rarr.shape

(14, 3, 2, 8)

In [54]:
np.ndim(rarr)

4

In [55]:
np.rollaxis(rarr, 2, start=0).shape

(2, 14, 3, 8)

In [56]:
np.moveaxis(rarr, [0,1,2,3], [1,0,3,2]).shape

(3, 14, 8, 2)

In [57]:
rarr[...,np.newaxis].shape

(14, 3, 2, 8, 1)

In [58]:
np.expand_dims(rarr, axis=2).shape

(14, 3, 1, 2, 8)

In [59]:
np.array([1.3]).item()

1.3

In [60]:
arrsplit = np.split(rarr, 2)
len(arrsplit)

2

In [61]:
arrsplit[0].shape

(7, 3, 2, 8)

In [62]:
arrsplit = np.split(rarr, 2, axis=2)
arrsplit[0].shape

(14, 3, 1, 8)

### 2.3 linear algebra (```numpy.linalg```)
See the list of functions [here](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [63]:
from numpy.linalg import norm, multi_dot
import numpy.linalg as nplin

In [64]:
norm([3,4])

5.0

In [65]:
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

In [66]:
%timeit A.dot(B).dot(C).dot(D)

106 ms ± 4.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [67]:
%timeit multi_dot([A, B, C, D])

21.2 ms ± 694 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [68]:
np.prod(np.isclose(A.dot(B).dot(C).dot(D), multi_dot([A, B, C, D]), atol=1e-8))

1

In [69]:
print(dir(nplin))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'absolute_import', 'cholesky', 'cond', 'det', 'division', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'print_function', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


### 2.4 [array iteration](https://numpy.org/doc/stable/reference/arrays.nditer.html) (```numpy.nditer```)

In [70]:
A = (np.arange(12)**2).reshape(3,4)
A

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [71]:
it = np.nditer(A, flags=['multi_index'])
for val in it:
    print('index = {}, value = {}'.format(it.multi_index, val))

index = (0, 0), value = 0
index = (0, 1), value = 1
index = (0, 2), value = 4
index = (0, 3), value = 9
index = (1, 0), value = 16
index = (1, 1), value = 25
index = (1, 2), value = 36
index = (1, 3), value = 49
index = (2, 0), value = 64
index = (2, 1), value = 81
index = (2, 2), value = 100
index = (2, 3), value = 121


In [72]:
it = np.nditer(A, flags=['c_index'])
for val in it:
    print('index = {}, value = {}'.format(it.index, val))

index = 0, value = 0
index = 1, value = 1
index = 2, value = 4
index = 3, value = 9
index = 4, value = 16
index = 5, value = 25
index = 6, value = 36
index = 7, value = 49
index = 8, value = 64
index = 9, value = 81
index = 10, value = 100
index = 11, value = 121


numpy.nditer can be slower than nested for loops if the ndarray dimension is equal to or less than 3

### 2.5 Nan-avoiding operations and [masked array](https://numpy.org/doc/stable/reference/maskedarray.html) (```numpy.ma```)

In [73]:
nan_arr = np.array([[-1, 5, 3.], [np.nan, 10, 65536]])
np.max(nan_arr), np.min(nan_arr), np.nanmax(nan_arr), np.nanmin(nan_arr)

(nan, nan, 65536.0, -1.0)

In [74]:
[mth for mth in dir(np) if mth.startswith('nan')]

['nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar']

In [75]:
from numpy import ma

In [78]:
marr = ma.masked_invalid(nan_arr)
marr = ma.masked_where(marr > 256, marr)
marr

c:\programdata\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


masked_array(
  data=[[-1.0, 5.0, 3.0],
        [--, 10.0, --]],
  mask=[[False, False, False],
        [ True, False,  True]],
  fill_value=1e+20)

In [79]:
marr.mask

array([[False, False, False],
       [ True, False,  True]])

In [80]:
marr.min()

-1.0

## 3. [scipy](https://docs.scipy.org/doc/scipy/reference/) -- scientific computing

In [108]:
import scipy as sp
import pkgutil
import glob as g

In [111]:
# Print the path of the module on computer
sp.__path__

['C:\\Users\\rpatr\\AppData\\Roaming\\Python\\Python36\\site-packages\\scipy']

Brief look at all modules of ```scipy```

In [112]:
all_files = g.glob(sp.__path__[0] + '\\*')
all_modules = [name for _, name, _ in pkgutil.iter_modules(all_files)]

In [113]:
print(all_modules)

['_hierarchy', '_optimal_leaf_ordering', '_vq', 'hierarchy', 'setup', 'tests', 'vq', 'codata', 'constants', '_backend', '_basic', '_debug_backends', '_helper', '_pocketfft', '_realtransforms', 'basic', 'convolve', 'helper', 'pseudo_diffs', 'realtransforms', '_bvp', '_dop', '_ivp', '_ode', '_odepack', '_quad_vec', '_quadpack', '_quadrature', '_test_multivariate', '_test_odeint_banded', 'lsoda', 'odepack', 'quadpack', 'vode', '_bspl', '_bsplines', '_cubic', '_fitpack', '_fitpack_impl', '_pade', '_ppoly', 'dfitpack', 'fitpack', 'fitpack2', 'interpnd', 'interpnd_info', 'interpolate', 'ndgriddata', 'polyint', 'rbf', '_fortran', '_test_fortran', 'arff', 'harwell_boeing', 'idl', 'matlab', 'mmio', 'netcdf', 'wavfile', '_cython_signature_generator', '_decomp_cossin', '_decomp_ldl', '_decomp_polar', '_decomp_qz', '_decomp_update', '_expm_frechet', '_fblas', '_flapack', '_flinalg', '_generate_pyx', '_interpolative', '_interpolative_backend', '_matfuncs_inv_ssq', '_matfuncs_sqrtm', '_procrustes', 

In [129]:
def func_check(module):
    """ Return all callables that don't start with _ string
    """
    
    funcs = [func for func in dir(module) if not func.startswith('_')]
    
    return funcs

Brief look at all functions under ```scipy.constants```

In [114]:
import scipy.constants as const
print(dir(const))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

Brief look at all functions under ```scipy.fftpack```

In [130]:
import scipy.fftpack as fft
print(func_check(fft))

['basic', 'cc_diff', 'convolve', 'cs_diff', 'dct', 'dctn', 'diff', 'dst', 'dstn', 'fft', 'fft2', 'fftfreq', 'fftn', 'fftshift', 'helper', 'hilbert', 'idct', 'idctn', 'idst', 'idstn', 'ifft', 'ifft2', 'ifftn', 'ifftshift', 'ihilbert', 'irfft', 'itilbert', 'next_fast_len', 'pseudo_diffs', 'realtransforms', 'rfft', 'rfftfreq', 'sc_diff', 'shift', 'ss_diff', 'test', 'tilbert']


Brief look at all functions under ```scipy.optimize```

In [132]:
import scipy.optimize as opt
print(func_check(opt))

['BFGS', 'Bounds', 'HessianUpdateStrategy', 'LbfgsInvHessProduct', 'LinearConstraint', 'NonlinearConstraint', 'OptimizeResult', 'OptimizeWarning', 'RootResults', 'SR1', 'anderson', 'approx_fprime', 'basinhopping', 'bisect', 'bracket', 'brent', 'brenth', 'brentq', 'broyden1', 'broyden2', 'brute', 'check_grad', 'cobyla', 'curve_fit', 'diagbroyden', 'differential_evolution', 'dual_annealing', 'excitingmixing', 'fixed_point', 'fmin', 'fmin_bfgs', 'fmin_cg', 'fmin_cobyla', 'fmin_l_bfgs_b', 'fmin_ncg', 'fmin_powell', 'fmin_slsqp', 'fmin_tnc', 'fminbound', 'fsolve', 'golden', 'lbfgsb', 'least_squares', 'leastsq', 'line_search', 'linear_sum_assignment', 'linearmixing', 'linesearch', 'linprog', 'linprog_verbose_callback', 'lsq_linear', 'minimize', 'minimize_scalar', 'minpack', 'minpack2', 'moduleTNC', 'newton', 'newton_krylov', 'nnls', 'nonlin', 'optimize', 'ridder', 'root', 'root_scalar', 'rosen', 'rosen_der', 'rosen_hess', 'rosen_hess_prod', 'shgo', 'show_options', 'slsqp', 'test', 'tnc', 'to

#### Test minimization using the [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function)

In [133]:
from scipy.optimize import rosen, rosen_der, least_squares, fmin_bfgs

In [134]:
x0 = np.array([1.1, 1.1, 1.1], dtype=np.double)
xopt, fopt, gopt, Bopt, func_calls, grad_calls, warnflag = \
    fmin_bfgs(rosen, x0, fprime=rosen_der, maxiter=2000, full_output=True, retall=False)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 11
         Function evaluations: 17
         Gradient evaluations: 17


In [135]:
res = least_squares(rosen, x0, args=(), method='trf', verbose=1, max_nfev=1e5)

`gtol` termination condition is satisfied.
Function evaluations 5358, initial cost 2.9768e+00, final cost 1.2232e-11, first-order optimality 9.99e-09.


In [136]:
res

 active_mask: array([0., 0., 0.])
        cost: 1.2232453040284042e-11
         fun: array([4.94620118e-06])
        grad: array([-1.21177462e-09,  9.98767609e-09,  7.61218444e-09])
         jac: array([[-0.00024499,  0.00201926,  0.001539  ]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 5358
        njev: 5283
  optimality: 9.987676088305907e-09
      status: 1
     success: True
           x: array([1.00099107, 1.00198871, 1.00398906])